[package]
name = "oslog"
description = "A minimal safe wrapper around Apple's Logging system"
repository = "https://github.com/steven-joruk/oslog"
version = "0.2.0"
authors = ["Steven Joruk <steven@joruk.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
keywords = ["log", "logging", "macos", "apple"]
categories = ["development-tools::debugging"]

[features]
default = ["logger"]

# Enables support for the `log` crate.
logger = ["log"]

[dependencies]
log = { version = "0.4.14", default-features = false, features = ["std"], optional = true }

[build-dependencies]
cc = "1.0.73"
